name: '${project.name}'
version: '${project.version}'
main: '${project.groupId}.${project.name}'
api-version: 1.20
authors: [ Dreig_Michihi ]
description: '${project.description}'
depend: [packetevents, ProjectKorra]
softdepend: [Spirits, Hyperion, JedCore, ProjectAddons]
commands:
  dspkreload:
    description: Reload plugin
    usage: /<command>
    aliases:
      - damagesplashespkreload
permissions:
  dspk.command.reload:
    default: op
    description: Grants access to reload command.
  dspk.display.sum:
    default: true
    description: Shows damage sum instead of separate damage.
  dspk.display.joint:
    default: true
    description: When false - shows damage sum separate for each element.
  dspk.cansee:
    default: true
    description: Grants access to see damage splashes.