name: DamageSplashesPK
version: 1.3
main: me.dreig_michihi.damagesplashespk.DamageSplashesPK
api-version: 1.16
authors: [ Dreig_Michihi ]
description: See your damage!
depend: [ProtocolLib, ProjectKorra, Spirits, JedCore]
commands:
  dspkreload:
    description: Reload plugin
    usage: /<command>
    aliases:
      - damagesplashespkreload
permissions:
  dspk.command.reload:
    default: op
    description: Grants access to reload command.
  dspk.cansee:
    default: true
    description: Grants access to see damage splashes.