name: '${project.name}'
version: '${project.version}'
main: '${project.groupId}.${project.name}'
api-version: 1.16
authors: [ Dreig_Michihi ]
description: '${project.description}'
depend: [ProtocolLib, ProjectKorra]
softdepend: [Spirits, Hyperion, JedCore, ProjectAddons]
commands:
  dspkreload:
    description: Reload plugin
    usage: /<command>
    aliases:
      - damagesplashespkreload
permissions:
  dspk.command.reload:
    default: op
    description: Grants access to reload command.
  dspk.command.toggle:
    default: true
    description: Grants access to reload command.
  dspk.cansee:
    default: true
    description: Grants access to see damage splashes.